name: php-lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: PHP lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.2' ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Lint PHP files
        run: |
          set -euo pipefail
          find . \
            -type d \( -path './vendor' -o -path './old' \) -prune -o \
            -type f -name '*.php' -print0 \
          | xargs -0 -n1 php -l